// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using przykladowykolos.Context;

#nullable disable

namespace przykladowykolos.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("przykladowykolos.Models.Album", b =>
                {
                    b.Property<int>("IdAlbum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAlbum"));

                    b.Property<DateTime>("DataWydania")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdWytwornia")
                        .HasColumnType("int");

                    b.Property<string>("NazwaAlbumu")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdAlbum");

                    b.HasIndex("IdWytwornia");

                    b.ToTable("Album", (string)null);
                });

            modelBuilder.Entity("przykladowykolos.Models.Muzyk", b =>
                {
                    b.Property<int>("IdMuzyk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMuzyk"));

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Pseudonim")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdMuzyk");

                    b.ToTable("Muzyk", (string)null);
                });

            modelBuilder.Entity("przykladowykolos.Models.Utwor", b =>
                {
                    b.Property<int>("IdUtwor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUtwor"));

                    b.Property<float>("CzasTrwania")
                        .HasColumnType("real");

                    b.Property<int?>("IdAlbum")
                        .HasColumnType("int");

                    b.Property<string>("NazwaUtworu")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdUtwor");

                    b.HasIndex("IdAlbum");

                    b.ToTable("Utwor", (string)null);
                });

            modelBuilder.Entity("przykladowykolos.Models.WykonawcaUtworu", b =>
                {
                    b.Property<int>("IdMuzyk")
                        .HasColumnType("int");

                    b.Property<int>("IdUtwor")
                        .HasColumnType("int");

                    b.HasKey("IdMuzyk", "IdUtwor");

                    b.HasIndex("IdUtwor");

                    b.ToTable("WykonawcaUtworu", (string)null);
                });

            modelBuilder.Entity("przykladowykolos.Models.Wytwornia", b =>
                {
                    b.Property<int>("IdWytwornia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdWytwornia"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdWytwornia");

                    b.ToTable("Wytwornia", (string)null);
                });

            modelBuilder.Entity("przykladowykolos.Models.Album", b =>
                {
                    b.HasOne("przykladowykolos.Models.Wytwornia", "idWytworniaNagivation")
                        .WithMany("Albums")
                        .HasForeignKey("IdWytwornia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("idWytworniaNagivation");
                });

            modelBuilder.Entity("przykladowykolos.Models.Utwor", b =>
                {
                    b.HasOne("przykladowykolos.Models.Album", "IdAlbumNavigation")
                        .WithMany("Utwors")
                        .HasForeignKey("IdAlbum")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("IdAlbumNavigation");
                });

            modelBuilder.Entity("przykladowykolos.Models.WykonawcaUtworu", b =>
                {
                    b.HasOne("przykladowykolos.Models.Muzyk", "IdMuzykNavigation")
                        .WithMany("WykonawcaUtworu")
                        .HasForeignKey("IdMuzyk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("przykladowykolos.Models.Utwor", "IdUtworNavigation")
                        .WithMany("WykonawcaUtworu")
                        .HasForeignKey("IdUtwor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdMuzykNavigation");

                    b.Navigation("IdUtworNavigation");
                });

            modelBuilder.Entity("przykladowykolos.Models.Album", b =>
                {
                    b.Navigation("Utwors");
                });

            modelBuilder.Entity("przykladowykolos.Models.Muzyk", b =>
                {
                    b.Navigation("WykonawcaUtworu");
                });

            modelBuilder.Entity("przykladowykolos.Models.Utwor", b =>
                {
                    b.Navigation("WykonawcaUtworu");
                });

            modelBuilder.Entity("przykladowykolos.Models.Wytwornia", b =>
                {
                    b.Navigation("Albums");
                });
#pragma warning restore 612, 618
        }
    }
}
